
build:
  version: "1.0"


accounts:
  message: "Welcome to Eazy Bank cards related Prod Apis"
  contactDetails:
    name: "Smith Ray- Prod Lead"
    email: "smith@helpinfo.com"
  onCallSupport:
    -(555)555-1238
    -(555)555-1239