
build:
  version: "3.0"

cards:
  message: "Welcome to Eazy Bank cards related local Apis"
  contactDetails:
    name: "John Doe- Developer"
    email: "john@helpinfo.com"
  onCallSupport:
    -(555)555-1234
    -(555)555-1235

