services:
  accounts:
    image: "prakash2021/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  cards:
    image: "prakash2021/cards:s4"
    container_name: cards-ms
    ports:
      - "8090:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  loans:
    image: "prakash2021/loans:s4"
    container_name: loans-ms
    ports:
      - "8091:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

networks:
  eazybank:
    driver: "bridge"
