server:
  port: 8081
spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

build:
  version: "3.0"

cards:
  message: "Welcome to Eazy Bank cards related local Apis"
  contactDetails:
    name: "John Doe- Developer"
    email: "john@helpinfo.com"
  onCallSupport:
    -(555)555-1234
    -(555)555-1235

